// Generated by CoffeeScript 1.6.3
var cities, cityArray, fs, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

fs = require('fs');

cityArray = JSON.parse(fs.readFileSync("" + __dirname + "/../data/city.json", "utf-8"));

cities = function() {
  return cityArray;
};

module.exports = {
  cities: cities
};
